"""Markdown report renderer for MethodBond evaluation results."""

from __future__ import annotations

from typing import Any


def render(result: dict[str, Any]) -> str:
    """Render an evaluation result as Markdown."""
    lines: list[str] = []
    lines.append("# MethodBond Evaluation Report")
    lines.append("")
    lines.append(f"- **Artifact ID:** `{result.get('artifact_id', 'unknown')}`")
    lines.append(f"- **Verdict:** `{result.get('verdict', 'unknown')}`")
    lines.append("")

    details = result.get("details", {})
    lines.append("## License Check")
    license_detail = details.get("license", {})
    if license_detail.get("errors"):
        for err in license_detail["errors"]:
            lines.append(f"- ❌ {err}")
    else:
        lines.append("- ✅ License metadata complete and valid.")
    lines.append("")

    lines.append("## Reproducibility Check")
    repro_detail = details.get("reproducibility", {})
    lines.append(f"- Independent provenances: {repro_detail.get('provenance_count', 0)}")
    if repro_detail.get("errors"):
        for err in repro_detail["errors"]:
            lines.append(f"- ❌ {err}")
    else:
        lines.append("- ✅ Output hashes agree across provenances.")
    lines.append("")

    lines.append("## Certification Check")
    cert_detail = details.get("certification", {})
    lines.append(f"- Baseline rules: {cert_detail.get('baseline_rules', 0)}")
    lines.append(f"- Candidate rules: {cert_detail.get('candidate_rules', 0)}")
    drifts = cert_detail.get("drifts", [])
    if drifts:
        for drift in drifts:
            lines.append(f"- ⚠️ {drift}")
    else:
        lines.append("- ✅ No baseline drift detected.")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by MethodBond — stdlib-only method-publishing trust-bundle gate.*")
    return "\n".join(lines)
